networks:
  traefik-network:
    external: true

services:
  server:
    image: insb-fastapi-email
    container_name: insb-fastapi-email
    volumes:
      - /home/robert/insblue-fastapi-email/app:/app
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.email.rule=(Host(`api.incdsb.ro`) && PathPrefix(`/_services/email/`))"
      - "traefik.http.routers.email.tls=true"
      - "traefik.http.services.email.loadbalancer.server.port=8000"
      - "traefik.http.routers.email.middlewares=email-stripprefix,oauth@docker"
      - "traefik.http.middlewares.email-stripprefix.stripprefix.prefixes=/_services/email/"


