VERSION_MAJOR = 0
VERSION_MINOR = 0
VERSION_BUILD = 1
VERSION_INFO = (VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD)
VERSION_STRING = "%d.%d.%d" % VERSION_INFO
AUTHOR_NAME = "Eduard C. Milea"
DESCRIPTION = "FORMS - FormIO module"
AUTHOR_EMAIL = "eduard.milea@incdsb.ro"

__version__ = VERSION_INFO
